# =====================================================
# MONEY STYLE SCANNER
# CLOUDFLARE WORKER CONFIG
# =====================================================

name = "money-style"

main = "worker.js"

compatibility_date = "2026-08-14"

workers_dev = true

[secrets]
required = ["ZAPI_API_KEY"]
